---
- name: Test connect to servers
  hosts: AppServers
  become: yes
    apt: upgrade=yes update_cache=yes cache_valid_time=86400

  tasks: 
  - name: Ping to servers
    ping:

  - name: Install Java
    apt: name=default-jdk state=latest
    
  - name: Install Maven
    apt: 
      name: maven

  - name: Install GIT
    apt: name=git state=latest  

  - name: Git clone repo
    ansible.builtin.git:
      repo: https://github.com/spring-projects/spring-petclinic.git  #TODO: Why no git file in my cloned repo
      dest: /src/petclinic
    
  - name: Run PetClinic
    shell: "cd /src/petclinic"
    shell: "pwd"
    shell: "mvn --version"
    shell: "mvn package"
    # shell: "java -jar target/*.jar"