---
- name: Test connect to servers
  hosts: AppServers
  become: yes

  tasks: 
  - name: Ping to servers
    ping:

  - name: Install Java and Maven
    apt: name=openjdk-16-jdk-headless state=latest

  - name: Install Maven
    apt: name=maven state=latest

  - name: Install GIT
    apt: name=git state=latest  

  - name: Git clone repo
    ansible.builtin.git:
      repo: https://github.com/spring-projects/spring-petclinic.git  #TODO: Why no git file in my cloned repo
      dest: /src/petclinic
    
  - name: Run PetClinic
    shell: "cd /src/petclinic"
    shell: "pwd"
    shell: "mvn --version"
    shell: "mvn package"
    # shell: "java -jar target/*.jar"